trigger:
- master
- develop
- net5

stages:
- stage: BuildTest
  displayName: Build & Test
  jobs:
  - job: buildtest
    displayName: buildtest
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: jobs/default-build.yml

