trigger:
- master
- develop
- net5

variables:
  isNet5: $[eq(variables['Build.SourceBranch'], 'refs/heads/net5')]


stages:
- stage: Build & Test
  jobs:
  - job: masterdev
    displayName: masterdev
    condition: and(failed(), eq(variables.isNet5, true))
    steps:
        - template: jobs/default-build.yml
          parameters:
            name: Linux
            vmImage: 'ubuntu-latest'
            useDotNet: '3.1.x'

  - job: net5
    displayName: net5
    condition: and(succeeded(), eq(variables.isNet5, true))
    steps:
        - template: jobs/default-build.yml
          parameters:
            name: Linux
            vmImage: 'ubuntu-latest'
            useDotNet: '5.0.100'