trigger:
- master
- develop
- net5


jobs:
- template: jobs/default-build.yml
  parameters:
    name: Linux
    vmImage: 'ubuntu-latest'

- template: jobs/default-build.yml
  parameters:
    name: macOS
    vmImage: 'macOS-latest'
