trigger:
- master
- develop
- net5

stages:
- stage: Build
  jobs:
  - job: Build: Default
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: jobs/default-build.yml

- stage: Test
  jobs:
  - job: Test: Default
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: jobs/default-test.yml
