trigger:
- master
- develop
- net5

stages:
- stage: BuildTest
  jobs:
  - job: master
    displayName: master
    pool:
      vmImage: ubuntu-latest
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
    steps:
        - template: jobs/default-build.yml
          parameters:
            useDotNet: '3.1.x'

  - job: develop
    displayName: develop
    pool:
      vmImage: ubuntu-latest
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'develop'))
    steps:
        - template: jobs/default-build.yml
          parameters:
            useDotNet: '3.1.x'

  - job: net5
    displayName: net5
    pool:
      vmImage: ubuntu-latest
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'net5'))
    steps:
        - template: jobs/default-build.yml
          parameters:
            useDotNet: '5.0.100'
