trigger:
- master
- develop
- net5

variables:
  isNet5: $[eq(variables['Build.SourceBranch'], 'refs/heads/net5')]


jobs:
- template: jobs/default-build.yml
  parameters:
    name: Linux
    vmImage: 'ubuntu-latest'
    condition: and(failed(), eq(variables.isNet5, true))

- template: jobs/default-build.yml
  parameters:
    name: Linux
    vmImage: 'ubuntu-latest'
    useDotNet: '5.0.100'
    condition: and(succeeded(), eq(variables.isNet5, true))