trigger:
- master
- develop
- net5

stages:
- stage: Test1
  jobs:
  - job: master
    displayName: master
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    steps:
        - template: jobs/default-build.yml
          parameters:
            name: Linux
            vmImage: 'ubuntu-latest'
            useDotNet: '3.1.x'

  - job: develop
    displayName: develop
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
    steps:
        - template: jobs/default-build.yml
          parameters:
            name: Linux
            vmImage: 'ubuntu-latest'
            useDotNet: '3.1.x'

  - job: net5
    displayName: net5
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/net5'))
    steps:
        - template: jobs/default-build.yml
          parameters:
            name: Linux
            vmImage: 'ubuntu-latest'
            useDotNet: '5.0.100'