parameters:
- name: name
  default: ''
- name: vmImage
  default: ''
- name: useDotNet
  default: '3.1.x'

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}

  steps:
  - task: UseDotNet@2
    inputs:
      version: ${{ parameters.useDotNet }}

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: 'build'
      projects: 'src/MudBlazor.sln'
      arguments: '--configuration Release'

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: 'test'
      projects: 'src/MudBlazor.UnitTests/MudBlazor.UnitTests.csproj'
      testRunTitle: 'UnitTests'
